language: cpp
os: linux
dist: xenial
#sudo: required
before_install:
   - PYCMD=$(which python3)
   - echo $PYCMD
   - sudo -H $PYCMD -m pip install --upgrade pip
   - sudo -H $PYCMD -m pip install --upgrade pytest
   - git clone https://github.com/pybind/pybind11.git; cd pybind11; git checkout stable; cd ..
install:
   - echo $PYCMD
   - cd pybind11; mkdir build; cd build; cmake .. -DPYTHON_EXECUTABLE=$PYCMD; sudo make install; cd ../..
script:
   - echo $PYCMD
   - CXX=g++-9 cmake -DPYTHON_EXECUTABLE=$PYCMD -DUSE_PYBIND_BINDINGS=ON -DUSE_PYTHON_EXTENSION=ON -DENABLE_COVERAGE:BOOL=TRUE .
   - make -j 2
   - make test
   #Comment out various unrelated messages
   #- bash <(curl -s https://codecov.io/bash)
   
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - g++-9
         - binutils-gold
         - python3
         - python3-pip
         - python3-dev
         - python3-setuptools
         - python3-pytest
