language: cpp
script:
   - CXX=g++-5.4 cmake -DUSE_PYTHON_BINDINGS=ON -DENABLE_COVERAGE:BOOL=TRUE .
   - make
   - make test
   - bash <(curl -s https://codecov.io/bash)
   
sudo: false
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - libboost-python-dev
         - g++-4.8
         - binutils-gold
